if(Books.find().count()==0){
	Books.insert({
		title:'新内容创业：我这样打造爆款IP',
		author:'曲林',
		year:'2016'
	});
	Books.insert({
		title:'为什么投你：一线投资人解密创业与投资的逻辑',
		author:'级铁溶',
		year:'2015'
	});
	Books.insert({
		title:'自品牌：个人如何玩转移动互联网时代',
		author:'孙玉婷',
		year:'2016'
	});
	Books.insert({
		title:'你是一桩独一无二的生意',
		author:'李东旭',
		year:'2014'
	});
	Books.insert({
		title:'卓越转型：知识型员工价值实现的四大修炼',
		author:'王振林',
		year:'2016'
	});
	Books.insert({
		title:'思考线：让你的创意变为现实的最佳方法',
		author:'黛布拉.凯',
		year:'2013'
	})
}